### ISSUE TITLE
 @vitejs/plugin-legacy cannot be used together with wagmi, and there will be bigint errors in packaging

### ISSUE THREAD

**Issue by kingport** [fisand/vite-wagmi-starter#3]
hi, I would like to ask if @vitejs/plugin-legacy cannot be used together with wagmi, and there will be bigint errors in packaging

**Comment by zouhangwithsweet** [comment]
Wagmi & Viem use **native BigInt** for number. And babel doesn't support transforming BigInts. This is expected behavior. If you want use `@vitejs/plugin-legacy`. You can try to check code before this [commit 4c012](https://github.com/fisand/vite-wagmi-starter/commit/a7dab78edde92911a57802fc820c97693864c012)

**Comment by kingport** [comment]
ok thanks



发自我的iPhone


------------------ Original ------------------
From: zouhang ***@***.***&gt;
Date: Tue,Aug 29,2023 9:35 AM
To: fisand/vite-wagmi-starter ***@***.***&gt;
Cc: Dking ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [fisand/vite-wagmi-starter]  @vitejs/plugin-legacy cannot be usedtogether with wagmi, and there will be bigint errors in packaging (Issue #3)





 
Wagmi &amp; Viem use native BigInt for number. And babel doesn't support transforming BigInts. This is expected behavior. If you want use @vitejs/plugin-legacy. You can try to check code before this commit 4c012
